---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: logging
--- 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: elasticsearch
  namespace: logging
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch 
--- 
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: elasticsearch
roleRef:
  kind: ClusterRole
  name: elasticsearch
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: logging
--- 
apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging
  namespace: logging
spec:
  replicas: 1
  selector:
    k8s-app: elasticsearch-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
    spec:
      serviceAccount: elasticsearch
      containers:
      #- image: gcr.io/google-containers/elasticsearch:v5.6.4
      #- image: docker.elastic.co/elasticsearch/elasticsearch5:5.2
      #- image: blacktop/elasticsearch:5.3
      #- image: gcr.io/google-containers/elasticsearch:v5.6.4
      - image: launcher.gcr.io/google/elasticsearch5:5.2
        imagePullPolicy: IfNotPresent
        name: elasticsearch-logging
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /data
          name: es-ephemeral-storage
      volumes:
      - emptyDir: {}
        name: es-ephemeral-storage
---
apiVersion: v1   
kind: Service   
metadata:
  labels:
    k8s-app: elasticsearch-logging   
    kubernetes.io/cluster-service: "true"   
    kubernetes.io/name: Elasticsearch   
  name: elasticsearch-logging   
  namespace: logging   
spec:
  ports:
    -
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    k8s-app: elasticsearch-logging   
  type: ClusterIP