---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-config
  namespace: kube-logging
data:
  pipeline.yml: "- pipeline.id: main\r\npath.config: \"/usr/share/logstash/config/*.conf\"\r\n"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: kube-logging
data:
  logstash.yml: |-
  http.host: 0.0.0.0
  http.port: 9600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-main-config
  namespace: kube-logging
data:
  logstash.conf: "
input {\r\n
  beats {\r\n
    port => \"5044\"\r\n
  }\r\n
}\r\n
output {\r\n
  elasticsearch {\r\n
    hosts => [\"http://elasticsearch:9200\"]\r\n
  }\r\n
}"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: logstash
  namespace: kube-logging
spec:
  template:
    metadata:
      labels:
        app: logstash
    spec:
      hostname: logstash
      containers:
      - name: logstash
        ports:
          - containerPort: 5044
            name: filebeat
          - containerPort: 9600
            name: logstash
        image: logstash:7.6.1
        volumeMounts:
        - name: logstash-pipeline-config-vm
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        # - name: logstash-config-vm
        #   mountPath: /usr/share/logstash/config
        #   readOnly: true
        command:
        - logstash
      volumes:
      # - name: logstash-pipeline-config-vm
      #   configMap:
      #     name: logstash-config
      #     items:
      #     - key: logstash.yml
      #       path: logstash.yml
      # - name: logstash-config-vm
      #   configMap:
      #     name: logstash-pipeline-config
      #     items:
      #     - key: pipeline.yml
      #       path: pipeline.yml
      - name: logstash-pipeline-config-vm
        configMap:
          name: logstash-pipeline-main-config
          items:
          - key: logstash.conf
            path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
  namespace: kube-logging
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    # nodePort: 30102
    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash